Repository KiraCore/sekai, pull requests merged in 2023-08, with the labels that each got.

#527 bugfix/499 -> release/v0.3.22
  types/constants.go
  x/custody/client/cli/query.go
Labels: kira-automation

#529 release/v0.3.22 -> latest
  types/constants.go
  x/custody/client/cli/query.go
Labels: kira-automation, automerge

#530 feature/custody_v2 -> release/v0.3.23
  types/constants.go
  x/custody/client/cli/query.go
Labels: kira-automation

#532 release/v0.3.23 -> latest
  types/constants.go
Labels: kira-automation, automerge

#534 bugfix/501 -> release/v0.3.24
  types/constants.go
  x/custody/client/cli/query.go
  x/gov/client/cli/query.go
Labels: kira-automation

#536 release/v0.3.24 -> latest
  types/constants.go
  x/gov/client/cli/query.go
Labels: kira-automation, automerge

#528 release/v0.3.22 -> master
  types/constants.go
  x/custody/client/cli/query.go
Labels: kira-automation

#537 bugfix/502 -> release/v0.3.25
  types/constants.go
  x/custody/client/cli/query.go
  x/gov/client/cli/query.go
  x/spending/client/cli/tx.go
Labels: kira-automation

#539 release/v0.3.25 -> latest
  types/constants.go
  x/spending/client/cli/tx.go
Labels: kira-automation, automerge

#542 release/v0.3.26 -> latest
  scripts/sekai-utils.sh
  types/constants.go
Labels: kira-automation, automerge

#541 release/v0.3.26 -> master
  scripts/sekai-utils.sh
  types/constants.go
  x/gov/client/cli/query.go
  x/spending/client/cli/tx.go
Labels: kira-automation

#544 feature/implement_missing_proposal_by_voter_query_filter -> release/v0.3.27
  RELEASE.md
  scripts/commands/adding-validators.sh
  types/constants.go
  x/gov/client/cli/query.go
  x/gov/keeper/grpc_query.go
  x/gov/types/network_properties.go
Labels: kira-automation

#545 release/v0.3.27 -> master
  RELEASE.md
  scripts/commands/adding-validators.sh
  types/constants.go
  x/gov/client/cli/query.go
  x/gov/keeper/grpc_query.go
  x/gov/types/network_properties.go
Labels: kira-automation

#533 Implement missing proposal by voter query filter
  RELEASE.md
  scripts/commands/adding-validators.sh
  types/constants.go
  x/gov/client/cli/query.go
  x/gov/keeper/grpc_query.go
  x/gov/types/network_properties.go
Labels: invalid

#549 feature/periodic_snapshot_inflation -> release/v0.3.28
  RELEASE.md
  proto/kira/distributor/genesis.proto
  proto/kira/distributor/query.proto
  types/constants.go
  x/distributor/client/cli/query.go
  x/distributor/keeper/abci.go
  x/distributor/keeper/annual_inflation.go
  x/distributor/keeper/annual_inflation_test.go
  x/distributor/keeper/distributor.go
  x/distributor/keeper/distributor_test.go
  x/distributor/keeper/grpc_query.go
  x/distributor/keeper/periodic_inflation.go
  x/distributor/keeper/periodic_inflation_test.go
  x/distributor/module.go
  x/distributor/types/genesis.pb.go
  x/distributor/types/keys.go
  x/distributor/types/query.pb.go
  x/distributor/types/query.pb.gw.go
Labels: kira-automation

#551 release/v0.3.28 -> latest
  RELEASE.md
  proto/kira/distributor/genesis.proto
  proto/kira/distributor/query.proto
  types/constants.go
  x/distributor/client/cli/query.go
  x/distributor/keeper/abci.go
  x/distributor/keeper/annual_inflation.go
  x/distributor/keeper/annual_inflation_test.go
  x/distributor/keeper/distributor.go
  x/distributor/keeper/distributor_test.go
  x/distributor/keeper/grpc_query.go
  x/distributor/keeper/periodic_inflation.go
  x/distributor/keeper/periodic_inflation_test.go
  x/distributor/module.go
  x/distributor/types/genesis.pb.go
  x/distributor/types/keys.go
  x/distributor/types/query.pb.go
  x/distributor/types/query.pb.gw.go
Labels: kira-automation, automerge

#550 release/v0.3.28 -> master
  RELEASE.md
  proto/kira/distributor/genesis.proto
  proto/kira/distributor/query.proto
  types/constants.go
  x/distributor/client/cli/query.go
  x/distributor/keeper/abci.go
  x/distributor/keeper/annual_inflation.go
  x/distributor/keeper/annual_inflation_test.go
  x/distributor/keeper/distributor.go
  x/distributor/keeper/distributor_test.go
  x/distributor/keeper/grpc_query.go
  x/distributor/keeper/periodic_inflation.go
  x/distributor/keeper/periodic_inflation_test.go
  x/distributor/module.go
  x/distributor/types/genesis.pb.go
  x/distributor/types/keys.go
  x/distributor/types/query.pb.go
  x/distributor/types/query.pb.gw.go
Labels: kira-automation
