Repository KiraCore/sekai, pull requests merged in 2023-11, with the labels that each got.

#599 Bugfix/gf cosign installer commit
  .github/workflows/main.yml
Labels: invalid

#601 feature/basket_module_updates -> release/v0.3.37
  RELEASE.md
  app/app.go
  proto/kira/basket/genesis.proto
  proto/kira/spending/pool.proto
  types/constants.go
  x/basket/keeper/basket.go
  x/basket/keeper/hooks.go
  x/basket/keeper/keeper.go
  x/basket/keeper/mint_burn_swap.go
  x/basket/keeper/mint_burn_swap_test.go
  x/basket/module.go
  x/basket/types/basket.go
  x/basket/types/errors.go
  x/basket/types/expected_keepers.go
  x/basket/types/genesis.go
  x/basket/types/genesis.pb.go
  x/gov/client/cli/cli_permission_test.go
  x/gov/types/query.pb.go
  x/gov/types/query.pb.gw.go
  x/layer2/keeper/abci.go
  x/multistaking/keeper/delegation.go
  x/multistaking/keeper/keeper.go
  x/multistaking/keeper/msg_server.go
  x/multistaking/keeper/pool.go
  x/multistaking/keeper/slash.go
  x/multistaking/types/expected_keepers.go
  x/multistaking/types/hooks.go
  x/multistaking/types/pool.go
  x/slashing/keeper/jail.go
  x/slashing/keeper/keeper.go
  x/slashing/types/expected_keepers.go
  x/slashing/types/hooks.go
  x/spending/client/cli/tx.go
  x/spending/keeper/abci.go
  x/spending/keeper/abci_test.go
  x/spending/keeper/keeper.go
  x/spending/keeper/keeper_test.go
  x/spending/keeper/spending_pool.go
  x/spending/keeper/spending_pool_test.go
  x/spending/types/genesis.go
  x/spending/types/msg.go
  x/spending/types/pool.pb.go
  x/tokens/handler_test.go
  x/tokens/keeper/grpc_query.go
  x/tokens/keeper/rate.go
  x/tokens/keeper/rate_test.go
  x/tokens/module.go
Labels: kira-automation

#604 feature/basket_module_updates -> release/v0.3.37
  .github/workflows/main.yml
Labels: kira-automation

#605 feature/basket_module_updates -> release/v0.3.37
  .github/workflows/main.yml
Labels: kira-automation

#607 feature/basket_module_updates -> release/v0.3.37
  .github/workflows/main.yml
Labels: kira-automation

#608 feature/basket_module_updates_and_gf_v1 -> release/v0.3.37
  .github/workflows/main.yml
Labels: kira-automation

#609 feature/basket_module_updates_and_gf_v1 -> release/v0.3.37
  .github/workflows/main.yml
Labels: kira-automation

#610 release/v0.3.37 -> latest
  .github/workflows/main.yml
  RELEASE.md
  app/app.go
  proto/kira/basket/genesis.proto
  proto/kira/spending/pool.proto
  types/constants.go
  x/basket/keeper/basket.go
  x/basket/keeper/hooks.go
  x/basket/keeper/keeper.go
  x/basket/keeper/mint_burn_swap.go
  x/basket/keeper/mint_burn_swap_test.go
  x/basket/module.go
  x/basket/types/basket.go
  x/basket/types/errors.go
  x/basket/types/expected_keepers.go
  x/basket/types/genesis.go
  x/basket/types/genesis.pb.go
  x/gov/client/cli/cli_permission_test.go
  x/gov/types/query.pb.go
  x/gov/types/query.pb.gw.go
  x/layer2/keeper/abci.go
  x/multistaking/keeper/delegation.go
  x/multistaking/keeper/keeper.go
  x/multistaking/keeper/msg_server.go
  x/multistaking/keeper/pool.go
  x/multistaking/keeper/slash.go
  x/multistaking/types/expected_keepers.go
  x/multistaking/types/hooks.go
  x/multistaking/types/pool.go
  x/slashing/keeper/jail.go
  x/slashing/keeper/keeper.go
  x/slashing/types/expected_keepers.go
  x/slashing/types/hooks.go
  x/spending/client/cli/tx.go
  x/spending/keeper/abci.go
  x/spending/keeper/abci_test.go
  x/spending/keeper/keeper.go
  x/spending/keeper/keeper_test.go
  x/spending/keeper/spending_pool.go
  x/spending/keeper/spending_pool_test.go
  x/spending/types/genesis.go
  x/spending/types/msg.go
  x/spending/types/pool.pb.go
  x/tokens/handler_test.go
  x/tokens/keeper/grpc_query.go
  x/tokens/keeper/rate.go
  x/tokens/keeper/rate_test.go
  x/tokens/module.go
Labels: kira-automation, automerge

#602 release/v0.3.37 -> master
  .github/workflows/main.yml
  RELEASE.md
  app/app.go
  proto/kira/basket/genesis.proto
  proto/kira/spending/pool.proto
  types/constants.go
  x/basket/keeper/basket.go
  x/basket/keeper/hooks.go
  x/basket/keeper/keeper.go
  x/basket/keeper/mint_burn_swap.go
  x/basket/keeper/mint_burn_swap_test.go
  x/basket/module.go
  x/basket/types/basket.go
  x/basket/types/errors.go
  x/basket/types/expected_keepers.go
  x/basket/types/genesis.go
  x/basket/types/genesis.pb.go
  x/gov/client/cli/cli_permission_test.go
  x/gov/types/query.pb.go
  x/gov/types/query.pb.gw.go
  x/layer2/keeper/abci.go
  x/multistaking/keeper/delegation.go
  x/multistaking/keeper/keeper.go
  x/multistaking/keeper/msg_server.go
  x/multistaking/keeper/pool.go
  x/multistaking/keeper/slash.go
  x/multistaking/types/expected_keepers.go
  x/multistaking/types/hooks.go
  x/multistaking/types/pool.go
  x/slashing/keeper/jail.go
  x/slashing/keeper/keeper.go
  x/slashing/types/expected_keepers.go
  x/slashing/types/hooks.go
  x/spending/client/cli/tx.go
  x/spending/keeper/abci.go
  x/spending/keeper/abci_test.go
  x/spending/keeper/keeper.go
  x/spending/keeper/keeper_test.go
  x/spending/keeper/spending_pool.go
  x/spending/keeper/spending_pool_test.go
  x/spending/types/genesis.go
  x/spending/types/msg.go
  x/spending/types/pool.pb.go
  x/tokens/handler_test.go
  x/tokens/keeper/grpc_query.go
  x/tokens/keeper/rate.go
  x/tokens/keeper/rate_test.go
  x/tokens/module.go
Labels: kira-automation

#606 modify customgov param name in verifyIdentityRecord function
  scripts/sekai-utils.sh
Labels: bug

#612 feature/autocompound_interval_addition -> release/v0.3.38
  RELEASE.md
  proto/kira/gov/network_properties.proto
  proto/kira/multistaking/multistaking.proto
  scripts/sekai-utils.sh
  types/constants.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/genesis_test.go
  x/gov/keeper/keeper.go
  x/gov/types/genesis.go
  x/gov/types/network_properties.pb.go
  x/multistaking/keeper/delegation.go
  x/multistaking/keeper/delegation_test.go
  x/multistaking/types/multistaking.pb.go
Labels: kira-automation

#614 release/v0.3.38 -> latest
  RELEASE.md
  proto/kira/gov/network_properties.proto
  proto/kira/multistaking/multistaking.proto
  scripts/sekai-utils.sh
  types/constants.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/genesis_test.go
  x/gov/keeper/keeper.go
  x/gov/types/genesis.go
  x/gov/types/network_properties.pb.go
  x/multistaking/keeper/delegation.go
  x/multistaking/keeper/delegation_test.go
  x/multistaking/types/multistaking.pb.go
Labels: kira-automation, automerge

#584 Autocompound interval addition
  RELEASE.md
  proto/kira/gov/network_properties.proto
  proto/kira/multistaking/multistaking.proto
  scripts/sekai-utils.sh
  types/constants.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/genesis_test.go
  x/gov/keeper/keeper.go
  x/gov/types/genesis.go
  x/gov/types/network_properties.pb.go
  x/multistaking/keeper/delegation.go
  x/multistaking/keeper/delegation_test.go
  x/multistaking/types/multistaking.pb.go
Labels: invalid
