Repository KiraCore/sekai, pull requests merged in 2023-02, with the labels that each got.

#416 release/v0.3.7.31 -> master
  RELEASE.md
  app/app.go
  proto/kira/recovery/genesis.proto
  proto/kira/recovery/query.proto
  proto/kira/recovery/recovery.proto
  proto/kira/recovery/tx.proto
  scripts/commands/recovery.sh
  types/Msg.go
  types/constants.go
  x/collectives/keeper/collective.go
  x/collectives/keeper/collective_test.go
  x/collectives/keeper/grpc_query.go
  x/custody/keeper/custody.go
  x/gov/keeper/councilor.go
  x/gov/keeper/network_actor.go
  x/gov/keeper/proposal.go
  x/multistaking/keeper/compound.go
  x/multistaking/keeper/pool.go
  x/recovery/abci.go
  x/recovery/client/cli/flags.go
  x/recovery/client/cli/query.go
  x/recovery/client/cli/tx.go
  x/recovery/genesis.go
  x/recovery/handler.go
  x/recovery/keeper/grpc_query.go
  x/recovery/keeper/keeper.go
  x/recovery/keeper/keeper_test.go
  x/recovery/keeper/msg_server.go
  x/recovery/keeper/msg_server_test.go
  x/recovery/keeper/recovery.go
  x/recovery/keeper/recovery_test.go
  x/recovery/keeper/rotation.go
  x/recovery/keeper/rotation_test.go
  x/recovery/module.go
  x/recovery/types/codec.go
  x/recovery/types/errors.go
  x/recovery/types/events.go
  x/recovery/types/expected_keepers.go
  x/recovery/types/genesis.go
  x/recovery/types/genesis.pb.go
  x/recovery/types/keys.go
  x/recovery/types/msg.go
  x/recovery/types/query.pb.go
  x/recovery/types/query.pb.gw.go
  x/recovery/types/recovery.pb.go
  x/recovery/types/tx.pb.go
  x/spending/keeper/spending_pool.go
  x/staking/keeper/keeper.go
Labels: kira-automation

#414 Recovery module
  RELEASE.md
  app/app.go
  proto/kira/recovery/genesis.proto
  proto/kira/recovery/query.proto
  proto/kira/recovery/recovery.proto
  proto/kira/recovery/tx.proto
  scripts/commands/recovery.sh
  types/Msg.go
  types/constants.go
  x/collectives/keeper/collective.go
  x/collectives/keeper/collective_test.go
  x/collectives/keeper/grpc_query.go
  x/custody/keeper/custody.go
  x/gov/keeper/councilor.go
  x/gov/keeper/network_actor.go
  x/gov/keeper/proposal.go
  x/multistaking/keeper/compound.go
  x/multistaking/keeper/pool.go
  x/recovery/abci.go
  x/recovery/client/cli/flags.go
  x/recovery/client/cli/query.go
  x/recovery/client/cli/tx.go
  x/recovery/genesis.go
  x/recovery/handler.go
  x/recovery/keeper/grpc_query.go
  x/recovery/keeper/keeper.go
  x/recovery/keeper/keeper_test.go
  x/recovery/keeper/msg_server.go
  x/recovery/keeper/msg_server_test.go
  x/recovery/keeper/recovery.go
  x/recovery/keeper/recovery_test.go
  x/recovery/keeper/rotation.go
  x/recovery/keeper/rotation_test.go
  x/recovery/module.go
  x/recovery/types/codec.go
  x/recovery/types/errors.go
  x/recovery/types/events.go
  x/recovery/types/expected_keepers.go
  x/recovery/types/genesis.go
  x/recovery/types/genesis.pb.go
  x/recovery/types/keys.go
  x/recovery/types/msg.go
  x/recovery/types/query.pb.go
  x/recovery/types/query.pb.gw.go
  x/recovery/types/recovery.pb.go
  x/recovery/types/tx.pb.go
  x/spending/keeper/spending_pool.go
  x/staking/keeper/keeper.go
Labels: invalid

#421 release/v0.3.8.32 -> latest
  README.md
  RELEASE.md
  cmd/sekaid/main.go
  scripts/commands/governance/upgrade-plan.sh
  scripts/commands/metadata.sh
  types/constants.go
  x/genutil/client/cli/standard_genesis_export.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/types/network_properties.go
  x/gov/types/permission.go
Labels: kira-automation, automerge

#420 release/v0.3.8.32 -> master
  README.md
  RELEASE.md
  cmd/sekaid/main.go
  scripts/commands/governance/upgrade-plan.sh
  scripts/commands/metadata.sh
  types/constants.go
  x/genutil/client/cli/standard_genesis_export.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/types/network_properties.go
  x/gov/types/permission.go
Labels: kira-automation

#418 Feature/export minimized genesis
  README.md
  RELEASE.md
  cmd/sekaid/main.go
  scripts/commands/governance/upgrade-plan.sh
  scripts/commands/metadata.sh
  types/constants.go
  x/genutil/client/cli/standard_genesis_export.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/types/network_properties.go
  x/gov/types/permission.go
Labels: invalid

#423 feature/validator_recovery_token -> release/v0.3.9.33
  RELEASE.md
  app/app.go
  proto/kira/gov/network_properties.proto
  proto/kira/recovery/genesis.proto
  proto/kira/recovery/query.proto
  proto/kira/recovery/recovery.proto
  proto/kira/recovery/tx.proto
  scripts/commands/recovery.sh
  types/Msg.go
  types/constants.go
  x/custody/types/custody.pb.go
  x/custody/types/tx.pb.go
  x/distributor/keeper/distributor.go
  x/distributor/keeper/distributor_test.go
  x/distributor/keeper/keeper.go
  x/distributor/types/expected_keepers.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/genesis_test.go
  x/gov/keeper/keeper.go
  x/gov/types/genesis.go
  x/gov/types/network_properties.pb.go
  x/gov/types/proposal.go
  x/recovery/client/cli/query.go
  x/recovery/client/cli/tx.go
  x/recovery/genesis.go
  x/recovery/handler.go
  x/recovery/keeper/grpc_query.go
  x/recovery/keeper/msg_server.go
  x/recovery/keeper/msg_server_test.go
  x/recovery/keeper/recovery.go
  x/recovery/keeper/recovery_test.go
  x/recovery/keeper/rewards.go
  x/recovery/keeper/rewards_test.go
  x/recovery/keeper/rotation.go
  x/recovery/types/codec.go
  x/recovery/types/errors.go
  x/recovery/types/expected_keepers.go
  x/recovery/types/genesis.go
  x/recovery/types/genesis.pb.go
  x/recovery/types/keys.go
  x/recovery/types/msg.go
  x/recovery/types/query.pb.go
  x/recovery/types/query.pb.gw.go
  x/recovery/types/recovery.pb.go
  x/recovery/types/tx.pb.go
Labels: kira-automation

#425 release/v0.3.9.33 -> latest
  RELEASE.md
  app/app.go
  proto/kira/gov/network_properties.proto
  proto/kira/recovery/genesis.proto
  proto/kira/recovery/query.proto
  proto/kira/recovery/recovery.proto
  proto/kira/recovery/tx.proto
  scripts/commands/recovery.sh
  types/Msg.go
  types/constants.go
  x/custody/types/custody.pb.go
  x/custody/types/tx.pb.go
  x/distributor/keeper/distributor.go
  x/distributor/keeper/distributor_test.go
  x/distributor/keeper/keeper.go
  x/distributor/types/expected_keepers.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/genesis_test.go
  x/gov/keeper/keeper.go
  x/gov/types/genesis.go
  x/gov/types/network_properties.pb.go
  x/gov/types/proposal.go
  x/recovery/client/cli/query.go
  x/recovery/client/cli/tx.go
  x/recovery/genesis.go
  x/recovery/handler.go
  x/recovery/keeper/grpc_query.go
  x/recovery/keeper/msg_server.go
  x/recovery/keeper/msg_server_test.go
  x/recovery/keeper/recovery.go
  x/recovery/keeper/recovery_test.go
  x/recovery/keeper/rewards.go
  x/recovery/keeper/rewards_test.go
  x/recovery/keeper/rotation.go
  x/recovery/types/codec.go
  x/recovery/types/errors.go
  x/recovery/types/expected_keepers.go
  x/recovery/types/genesis.go
  x/recovery/types/genesis.pb.go
  x/recovery/types/keys.go
  x/recovery/types/msg.go
  x/recovery/types/query.pb.go
  x/recovery/types/query.pb.gw.go
  x/recovery/types/recovery.pb.go
  x/recovery/types/tx.pb.go
Labels: kira-automation, automerge

#424 release/v0.3.9.33 -> master
  RELEASE.md
  app/app.go
  proto/kira/gov/network_properties.proto
  proto/kira/recovery/genesis.proto
  proto/kira/recovery/query.proto
  proto/kira/recovery/recovery.proto
  proto/kira/recovery/tx.proto
  scripts/commands/recovery.sh
  types/Msg.go
  types/constants.go
  x/custody/types/custody.pb.go
  x/custody/types/tx.pb.go
  x/distributor/keeper/distributor.go
  x/distributor/keeper/distributor_test.go
  x/distributor/keeper/keeper.go
  x/distributor/types/expected_keepers.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/genesis_test.go
  x/gov/keeper/keeper.go
  x/gov/types/genesis.go
  x/gov/types/network_properties.pb.go
  x/gov/types/proposal.go
  x/recovery/client/cli/query.go
  x/recovery/client/cli/tx.go
  x/recovery/genesis.go
  x/recovery/handler.go
  x/recovery/keeper/grpc_query.go
  x/recovery/keeper/msg_server.go
  x/recovery/keeper/msg_server_test.go
  x/recovery/keeper/recovery.go
  x/recovery/keeper/recovery_test.go
  x/recovery/keeper/rewards.go
  x/recovery/keeper/rewards_test.go
  x/recovery/keeper/rotation.go
  x/recovery/types/codec.go
  x/recovery/types/errors.go
  x/recovery/types/expected_keepers.go
  x/recovery/types/genesis.go
  x/recovery/types/genesis.pb.go
  x/recovery/types/keys.go
  x/recovery/types/msg.go
  x/recovery/types/query.pb.go
  x/recovery/types/query.pb.gw.go
  x/recovery/types/recovery.pb.go
  x/recovery/types/tx.pb.go
Labels: kira-automation

#422 Validator recovery token
  RELEASE.md
  app/app.go
  proto/kira/gov/network_properties.proto
  proto/kira/recovery/genesis.proto
  proto/kira/recovery/query.proto
  proto/kira/recovery/recovery.proto
  proto/kira/recovery/tx.proto
  scripts/commands/recovery.sh
  types/Msg.go
  types/constants.go
  x/custody/types/custody.pb.go
  x/custody/types/tx.pb.go
  x/distributor/keeper/distributor.go
  x/distributor/keeper/distributor_test.go
  x/distributor/keeper/keeper.go
  x/distributor/types/expected_keepers.go
  x/genutil/client/cli/upgrade_genesis.go
  x/gov/genesis_test.go
  x/gov/keeper/keeper.go
  x/gov/types/genesis.go
  x/gov/types/network_properties.pb.go
  x/gov/types/proposal.go
  x/recovery/client/cli/query.go
  x/recovery/client/cli/tx.go
  x/recovery/genesis.go
  x/recovery/handler.go
  x/recovery/keeper/grpc_query.go
  x/recovery/keeper/msg_server.go
  x/recovery/keeper/msg_server_test.go
  x/recovery/keeper/recovery.go
  x/recovery/keeper/recovery_test.go
  x/recovery/keeper/rewards.go
  x/recovery/keeper/rewards_test.go
  x/recovery/keeper/rotation.go
  x/recovery/types/codec.go
  x/recovery/types/errors.go
  x/recovery/types/expected_keepers.go
  x/recovery/types/genesis.go
  x/recovery/types/genesis.pb.go
  x/recovery/types/keys.go
  x/recovery/types/msg.go
  x/recovery/types/query.pb.go
  x/recovery/types/query.pb.gw.go
  x/recovery/types/recovery.pb.go
  x/recovery/types/tx.pb.go
Labels: invalid
