Repository KiraCore/sekai, pull requests merged in 2025-03, with the labels that each got.

#691 bugfix/KIP-84 -> release/v0.4.2
  types/constants.go
  x/layer2/keeper/msg_server.go
Labels: kira-automation

#694 release/v0.4.2 -> master
  .github/workflows/main.yml
  types/constants.go
  x/layer2/keeper/msg_server.go
Labels: kira-automation

#690 Bugfix/kip 84
  types/constants.go
  x/layer2/keeper/msg_server.go
Labels: invalid

#695 feature/KIP-87_main -> release/v0.4.3
  .github/workflows/branch.yml
  .github/workflows/main.yml
  .github/workflows/master.yml
  .github/workflows/merge_hook.yml
  RELEASE.md
  app/app.go
  proto/kira/ethereum/ethereum.proto
  proto/kira/ethereum/genesis.proto
  proto/kira/ethereum/query.proto
  proto/kira/ethereum/tx.proto
  types/constants.go
  x/ethereum/client/cli/query.go
  x/ethereum/client/cli/tx.go
  x/ethereum/handler.go
  x/ethereum/keeper/ethereum.go
  x/ethereum/keeper/grpc_query.go
  x/ethereum/keeper/keeper.go
  x/ethereum/keeper/msg_server.go
  x/ethereum/module.go
  x/ethereum/types/codec.go
  x/ethereum/types/errors.go
  x/ethereum/types/ethereum.pb.go
  x/ethereum/types/expected_keepers.go
  x/ethereum/types/genesis.go
  x/ethereum/types/genesis.pb.go
  x/ethereum/types/keys.go
  x/ethereum/types/msg.go
  x/ethereum/types/query.pb.go
  x/ethereum/types/query.pb.gw.go
  x/ethereum/types/tx.pb.go
Labels: kira-automation

#697 release/v0.4.3 -> latest
  .github/workflows/branch.yml
  .github/workflows/main.yml
  .github/workflows/master.yml
  .github/workflows/merge_hook.yml
  RELEASE.md
  app/app.go
  proto/kira/ethereum/ethereum.proto
  proto/kira/ethereum/genesis.proto
  proto/kira/ethereum/query.proto
  proto/kira/ethereum/tx.proto
  types/constants.go
  x/ethereum/client/cli/query.go
  x/ethereum/client/cli/tx.go
  x/ethereum/handler.go
  x/ethereum/keeper/ethereum.go
  x/ethereum/keeper/grpc_query.go
  x/ethereum/keeper/keeper.go
  x/ethereum/keeper/msg_server.go
  x/ethereum/module.go
  x/ethereum/types/codec.go
  x/ethereum/types/errors.go
  x/ethereum/types/ethereum.pb.go
  x/ethereum/types/expected_keepers.go
  x/ethereum/types/genesis.go
  x/ethereum/types/genesis.pb.go
  x/ethereum/types/keys.go
  x/ethereum/types/msg.go
  x/ethereum/types/query.pb.go
  x/ethereum/types/query.pb.gw.go
  x/ethereum/types/tx.pb.go
  x/layer2/keeper/msg_server.go
Labels: kira-automation, automerge

#698 feature/KIP-87_extra -> release/v0.4.4
  scripts/sekai-utils.sh
  scripts/test-local/ethereum-processes.sh
  types/constants.go
  x/ethereum/keeper/msg_server.go
Labels: kira-automation

#700 release/v0.4.4 -> master
  scripts/sekai-utils.sh
  scripts/test-local/ethereum-processes.sh
  types/constants.go
  x/ethereum/keeper/msg_server.go
Labels: kira-automation
